[package]
name = "mermaid-worker"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Nachtalb <na@nachtalb.io>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = "0.8.7"
mermaid-rs-renderer = { git = "https://github.com/Nachtalb/mermaid-rs-renderer", branch = "worker", default-features = false }
resvg = { version = "0.47", default-features = false, features = ["text"] }
image-webp = "0.2"
ravif = { version = "0.13", default-features = false }
rgb = "0.8"

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
